/*
Alcance:
    Fuentes estáticas.
    Colecciones.
    Hechos: listado, filtrado y búsqueda.
    Visualizadores y Contribuyentes de hechos.
    Solicitudes de eliminación.
*/

@startuml
'https://plantuml.com/class-diagram

Multimedia --> Formato

Hecho --> Categoria
Hecho --> " * " Etiqueta
Hecho --> Ubicacion
Hecho --> Origen
Hecho --> Multimedia

Zona --> " * " Ubicacion

Origen --> TipoOrigen

Filtro --> Zona
Filtro --> Categoria
Filtro ..> Hecho

Coleccion --> " * " Hecho
Coleccion --> Filtro

Solicitud --> Hecho
Solicitud --> Estado

ImportadorHechos ..> Hecho
ImportadorHechos --> CsvReaderAdapter

class Categoria {
    - nombre: String
}

class Etiqueta {
    - nombre: String
}

class Ubicacion {
    - latitud: Integer
    - longitud: Integer
}

class Origen {
    - tipo: TipoOrigen
    - nombreAutor: String
    - apellidoAutor: String
    - edadAutor: Integer
}

enum TipoOrigen {
    MANUAL
    DATASET
    CONTRIBUYENTE
}

enum Formato {
    TEXTO
    IMAGEN
    AUDIO
    VIDEO
}

class Multimedia {
    - nombre: String
    - ruta: String
    - formato: Formato
}

class Hecho {
    - titulo: String
    - descripcion: String
    - categoria: Categoria
    - etiquetas: Set<Etiqueta>
    - ubicacion: Ubicacion
    - fechaAcontecimiento: LocalDate
    - fechaCarga: LocalDate
    - origen: Origen
    - multimedia: Multimedia
    - eliminado: Boolean
    + agregar(etiqueta: Etiqueta): Boolean
}

class Zona {
    - nombre: String,
    - perimetro: Set<Ubicacion>
    + pertenece(ubicacion: Ubicacion): Boolean
}

class Filtro {
    - titulo: 
    - categoria: Categoria
    - zona: Zona
    - fechaInicio: LocalDate
    - fechaFin: LocalDate
    + cumpleFiltro(hecho: Hecho): Boolean
}

class Coleccion {
    - titulo: String
    - descripcion: String
    - hechos: Set<Hecho>
    - criterios: Set<Filtro>
    + agregarHechos(hechos: Set<Hecho>): Boolean
    + eliminarHechos(titulos: List<String>): Boolean
}

enum Estado {
    PENDIENTE
    ACEPTADA
    RECHAZADA
}

class Solicitud {
   - titulo: String
   - texto: String
   - hecho: Hecho
   - estado: Estado
   - fecha: LocalDateTime
   - responsable: String
   - supervisor: String
   + estaFundado(): Boolean
}

class LectorCsv implements CsvReaderAdapter {
    + readCsv(path: String, separator: String): List<Object>
}

interface CsvReaderAdapter {
    + readCsv(path: String, separator: String): List<Object>
}

class ImportadorHechos {
    - csvReader: CsvReaderAdapter
    - rutaArchivo: String
    - separadorColumna: String
    + importarHechos(): Set<Hecho>
}

@enduml