/*
Alcance:
    Fuentes estáticas.
    Colecciones.
    Hechos: listado, filtrado y búsqueda.
    Visualizadores y Contribuyentes de hechos.
    Solicitudes de eliminación.
*/

@startuml
'https://plantuml.com/class-diagram

Multimedia --> Formato
Lugar --> TipoLugar

Hecho --> " * "Etiqueta
Hecho --> Ubicacion
Hecho --> Origen
Hecho --> Multimedia

Zona --> " * " Ubicacion

Ubicacion --> Lugar

Origen --> TipoOrigen

FiltroZonaStrategy --> Zona

FiltroTituloStrategy ..> Hecho
FiltroCategoriaStrategy ..> Hecho
FiltroFechaStrategy ..> Hecho
FiltroZonaStrategy ..> Hecho

Coleccion --> " * " FiltroStrategy
Coleccion --> " * " Fuente
Coleccion -->  IConsensoStrategy

Estado --> TipoEstado

Solicitud --> Hecho
Solicitud --> Estado

Fuente ..> FiltroStrategy
Fuente -->  TipoFuente
IConsensoStrategy --> TipoAlgoritmo
Fuente --> Hecho

class Etiqueta {
    - etiqueta : String
}

class Ubicacion {
    - latitud: Double
    - longitud: Double
    - direccion: String
    - referenciaLugar: Lugar
}

class Lugar {
    - nombre: String
    - tipo: TipoLugar
}

class Origen {
    - tipo: TipoOrigen
    - nombreAutor: String
    - apellidoAutor: String
    - edadAutor: Integer
}

enum TipoFuente {
    ESTATICA
    DINAMICA
    PROXY-API
    PROXY-METAMAPA
}

enum Formato {
    TEXTO
    IMAGEN
    AUDIO
    VIDEO
}

enum TipoLugar {
    LOCALIDAD
    MUNICIPIO
    PROVINCIA
}

enum TipoAlgoritmo{
    MULTIPLES_MENCIONES
    MAYORIA_SIMPLE
    ABSOLUTO
    + getStrategy() : IConsensoStrategy
}

class Multimedia {
    - nombre: String
    - ruta: String
    - formato: Formato
}

class Hecho {
    - titulo: String
    - descripcion: String
    - categoria: String
    - etiquetas: Set<Etiqueta>
    - ubicacion: Ubicacion
    - fechaAcontecimiento: LocalDate
    - fechaCarga: LocalDate
    - origen: Origen
    - multimedia: List<Multimedia>
    - eliminado: Boolean
    + agregar(etiqueta: Etiqueta): Boolean
    + convertirHechoDTOAHecho(HechoDTOEntrada dto, TipoFuente tipoFuente) : Hecho
}

class Zona {
    - nombre: String
    - perimetro: Set<Ubicacion>
    + pertenece(ubicacion: Ubicacion): Boolean
}



interface FiltroStrategy {
    + cumpleFiltro(hecho: Hecho): Boolean
}

class FiltroTituloStrategy implements FiltroStrategy {
    - titulo: String
    + cumpleFiltro(hecho: Hecho): Boolean
}

class FiltroCategoriaStrategy implements FiltroStrategy {
    - categoria: String
    + cumpleFiltro(hecho: Hecho): Boolean
}

class FiltroZonaStrategy implements FiltroStrategy {
    - zona: Zona
    + cumpleFiltro(hecho: Hecho): Boolean
}

class FiltroFechaStrategy implements FiltroStrategy {
    - fechaInicio: LocalDate
    - fechaFin: LocalDate
    + cumpleFiltro(hecho: Hecho): Boolean
}

class Coleccion {
    - id: String
    - titulo: String
    - descripcion: String
    - criterios: Set<FiltroStrategy>
    - fuentes: Set<IFuenteAbstract>
    - algoritmoConsenso: IAlgoritmoConsenso
    - hechosConsensuados : List<Hecho>
    + obtenerHechos(criterios: Set<FiltroStrategy>): Set<Hecho>
    + eliminarCriterio(FiltroStrategy filtro): void
    + agregarFuente(IFuenteAbstract fuente) : void
    + eliminarFuente(String idFuente) : void
    + actualizarHechosConsensuados() : void
    + actualizarFuentes() : void
}

abstract class IConsensoStrategy{
  -cumpleConsensoBase(Hecho hecho, Set<Fuente> fuentes, Set<IFiltroStrategy> filtros, Integer cantMin) : Boolean
  +Boolean cumpleConsenso(Hecho hecho, Set<Fuente> fuentes, Set<IFiltroStrategy> filtros) : Boolean
}

class ConsensoMultiplesMenciones extends IConsensoStrategy {
    +cumpleConsenso(Hecho hecho, Set<Fuente> fuentes, Set<IFiltroStrategy> filtros) : Boolean
}

class ConsensoAbsoluto extends IConsensoStrategy {
    +cumpleConsenso(Hecho hecho, Set<Fuente> fuentes, Set<IFiltroStrategy> filtros) : Boolean
}

class ConsensoMayorSimple extends IConsensoStrategy {
    +cumpleConsenso(Hecho hecho, Set<Fuente> fuentes, Set<IFiltroStrategy> filtros) : Boolean
}

abstract class Fuente {
  -id : String
  -url : String
  -tipoFuente : TipoFuente
  +convertirFuenteDTOAFuente(FuenteDTO dto) : Fuente
  +refrescarHechos() : void
  +getHechos(Set<IFiltroStrategy> filtros) : Set<Hecho>
  +cumpleFiltros(Set<IFiltroStrategy> filtros, Hecho hecho) : Boolean
}

class FuenteDefault extends Fuente {
   + refrescarHechos() : void
   + getHechos(Set<IFiltroStrategy> filtros) : Set<Hecho>
}

class FuenteProxyMetamapa extends Fuente {
   + refrescarHechos() : void
   + getHechos(Set<IFiltroStrategy> filtros) : Set<Hecho>
}

enum TipoEstado {
    PENDIENTE
    ACEPTADA
    RECHAZADA
}

class Estado {
   - estado: TipoEstado
   - fechaActualizacion: LocalDateTime
   - supervisor: String
}

class Solicitud {
    - id : String
    - titulo : String
    - texto : String
    - hecho : Hecho
    - estadoActual : Estado
    - fecha : LocalDateTime
    - responsable : String
    - supervisor : String
    - historial : List<Estado>
    + estaFundado() : Boolean
    + rechazar() : void
    + aceptar() : void
    + cambiarEstado(Estado estado) : void
    + estaAceptada () : Boolean
}

@enduml
