/*
Alcance:
    Fuentes estáticas.
    Colecciones.
    Hechos: listado, filtrado y búsqueda.
    Visualizadores y Contribuyentes de hechos.
    Solicitudes de eliminación.
*/

@startuml
'https://plantuml.com/class-diagram

Multimedia --> Formato
Lugar --> TipoLugar

Hecho --> " * "Etiqueta
Hecho --> Ubicacion
Hecho --> Origen
Hecho --> Multimedia

Zona --> " * " Ubicacion

Ubicacion --> Lugar

Origen --> TipoOrigen

FiltroZonaStrategy --> Zona

FiltroTituloStrategy ..> Hecho
FiltroCategoriaStrategy ..> Hecho
FiltroFechaStrategy ..> Hecho
FiltroZonaStrategy ..> Hecho

Coleccion --> " * " FiltroStrategy
Coleccion --> " * " IFuenteAbstract
Coleccion -->  IAlgoritmoConsenso
FuenteAdapter --> TipoOrigen

Estado --> TipoEstado

Solicitud --> Hecho
Solicitud --> Estado
Solicitud --> Motivo

IFuenteAbstract ..> FiltroStrategy


class Etiqueta {
    - etiqueta : String
}

class Ubicacion {
    - latitud: Double
    - longitud: Double
    - direccion: String
    - referenciaLugar: Lugar
}

class Lugar {
    - nombre: String
    - tipo: TipoLugar
}

class Origen {
    - tipo: TipoOrigen
    - nombreAutor: String
    - apellidoAutor: String
    - edadAutor: Integer
}

enum TipoOrigen {
    ESTATICA
    DINAMICA
    PROXY
}

enum Formato {
    TEXTO
    IMAGEN
    AUDIO
    VIDEO
}

enum TipoLugar {
    LOCALIDAD
    MUNICIPIO
    PROVINCIA
}

class Multimedia {
    - nombre: String
    - ruta: String
    - formato: Formato
}

class Hecho {
    - titulo: String
    - descripcion: String
    - categoria: String
    - etiquetas: Set<Etiqueta>
    - ubicacion: Ubicacion
    - fechaAcontecimiento: LocalDate
    - fechaCarga: LocalDate
    - origen: Origen
    - multimedia: List<Multimedia>
    - eliminado: Boolean
    + agregar(etiqueta: Etiqueta): Boolean
}

class Zona {
    - nombre: String
    - perimetro: Set<Ubicacion>
    + pertenece(ubicacion: Ubicacion): Boolean
}

interface IFuenteAbstract {
    + obtenerHechos(criterios: Set<FiltroStrategy>): Set<Hecho>
    + cumpleCriterios(Set<FiltroStrategy> criterios, Hecho hecho) : Boolean
    + getId() : String
    + obtenerHechosUrl(Integer page, Integer per_page) : FuenteResponseDTO
    + actualizarHechos() : void

}

class FuenteAbstract implements IFuenteAbstract{
     - id : String
     - url : String
     - tipoOrigen : TipoOrigen
     - hechos _: List<Hecho>
     - generadorId : IGeneradorIdAdapter
     + obtenerHechos(criterios: Set<FiltroStrategy>): Set<Hecho>
     + cumpleCriterios(Set<FiltroStrategy> criterios, Hecho hecho) : Boolean
     + getId() : String
     + obtenerHechosUrl(Integer page, Integer per_page) : FuenteResponseDTO
     + actualizarHechos() : void
}

class FuenteProxy extends FuenteAbstract {
    +obtenerHechos(Set<FiltroStrategy> criterios) : Set<Hecho>
    +actualizarHechos()
}

class FuenteDinamicaEstatica extends FuenteAbstract {

}

interface FiltroStrategy {
    + cumpleFiltro(hecho: Hecho): Boolean
}

class FiltroTituloStrategy implements FiltroStrategy {
    - titulo: String
    + cumpleFiltro(hecho: Hecho): Boolean
}

class FiltroCategoriaStrategy implements FiltroStrategy {
    - categoria: String
    + cumpleFiltro(hecho: Hecho): Boolean
}

class FiltroZonaStrategy implements FiltroStrategy {
    - zona: Zona
    + cumpleFiltro(hecho: Hecho): Boolean
}

class FiltroFechaStrategy implements FiltroStrategy {
    - fechaInicio: LocalDate
    - fechaFin: LocalDate
    + cumpleFiltro(hecho: Hecho): Boolean
}

class Coleccion {
    - id: String
    - titulo: String
    - descripcion: String
    - criterios: Set<FiltroStrategy>
    - fuentes: Set<IFuenteAbstract>
    - algoritmoConsenso: IAlgoritmoConsenso
    + obtenerHechos(criterios: Set<FiltroStrategy>): Set<Hecho>
    + obtenerHechosCurados: Set<Hecho>
}

interface IAlgoritmoConsenso {
    + convertirHechoDTOAHechoComparable(Object hecho) : Hecho
    + cumpleConsenso(Hecho hecho, Set<IFuenteAbstract> fuentes, Set<FiltroStrategy> criterios) : Boolean
    + obtenerHechosConsensuados(Set<IFuenteAbstract> fuentes, Set<FiltroStrategy> criterios) : Set<Hecho>
    + setCantMinimaApariciones(int cant) : void
}

abstract class AlgoritmoConsenso implements IAlgoritmoConsenso {
    - cantidadMinimaApariciones : int
    + setCantMinimaApariciones(int cant) : void
    + convertirHechoDTOAHechoComparable(Object hecho) : Hecho
    + cumpleConsenso(Hecho hecho, Set<IFuenteAbstract> fuentes, Set<FiltroStrategy> criterios) : Boolean
    + obtenerHechosConsensuados(Set<IFuenteAbstract> fuentes, Set<FiltroStrategy> criterios) : Set<Hecho>
}

class AlgoritmoMultiplesMenciones extends AlgoritmoConsenso {
    + cumpleConsenso(Hecho hecho, Set<IFuenteAbstract> fuentes, Set<FiltroStrategy> criterios) : Boolean
}

class AlgoritmoMayoriaAbsoluta extends AlgoritmoConsenso {
    + cumpleConsenso(Hecho hecho, Set<IFuenteAbstract> fuentes, Set<FiltroStrategy> criterios) : Boolean
}

class AlgoritmoIrrestricto extends AlgoritmoConsenso {
     + cumpleConsenso(Hecho hecho, Set<IFuenteAbstract> fuentes, Set<FiltroStrategy> criterios) : Boolean
}
enum TipoEstado {
    PENDIENTE
    ACEPTADA
    RECHAZADA
}

class Estado {
   - estado: TipoEstado
   - fechaActualizacion: LocalDateTime
   - supervisor: String
}

class Solicitud {
   - titulo: String
   - texto: String
   - hecho: Hecho
   - motivo: Motivo
   - fechaCreacion: LocalDateTime
   - responsable: String
   - estadoActual: Estado
   - historial: Set<Estado>
   + estaFundado(): Boolean
}

enum Motivo {
    ELIMINACION
    MODIFICACION
}

@enduml
